# TODO: Complete this Dockerfile to build your ASCII art image
# Hint: Start with a Python base image

# TODO: Choose a base image
# Hint: Use 'python:3.11-slim' for a lightweight Python image
FROM 

# TODO: Set working directory inside container
# Hint: Use WORKDIR to set where files will be placed
WORKDIR 

# TODO: Copy your Python script into the container
# Hint: COPY source destination
COPY 

# TODO: Set the command to run when container starts
# Hint: Use CMD to specify what runs by default
CMD 